version: '3.8'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1qaw3edr5*
      MYSQL_DATABASE: mercado_free
      MYSQL_USER: developer
      MYSQL_PASSWORD: santiagob0710
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://developer:santiagob0710@mysql/mercado_free

volumes:
  mysql_data: